/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/audio/{filename}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download Audio */
    get: operations["download_audio_api_audio__filename__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auto-generation/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run Auto Generation */
    post: operations["run_auto_generation_api_auto_generation_run_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bookmarks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Bookmarks */
    get: operations["list_bookmarks_api_bookmarks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bookmarks/audio/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Delete Bookmark Audio */
    post: operations["delete_bookmark_audio_api_bookmarks_audio_delete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bookmarks/auto-generation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set Auto Exclusion */
    put: operations["set_auto_exclusion_api_bookmarks_auto_generation_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Jobs
     * @description Queued, running and failed jobs. A completed job is its bookmark's audio.
     */
    get: operations["list_jobs_api_jobs_get"];
    put?: never;
    /** Create Jobs */
    post: operations["create_jobs_api_jobs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/bulk-delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bulk Delete Jobs */
    post: operations["bulk_delete_jobs_api_jobs_bulk_delete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/ids": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Job Ids */
    get: operations["list_job_ids_api_jobs_ids_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Job */
    get: operations["get_job_api_jobs__job_id__get"];
    put?: never;
    post?: never;
    /** Delete Job */
    delete: operations["delete_job_api_jobs__job_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{job_id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Retry Job */
    post: operations["retry_job_api_jobs__job_id__retry_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Settings */
    get: operations["get_settings_api_settings_get"];
    /** Update Settings */
    put: operations["update_settings_api_settings_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sync/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run Sync
     * @description Start a sync with Readeck in the background; poll the settings for its result.
     */
    post: operations["run_sync_api_sync_run_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Audio */
    Audio: {
      /** Filename */
      filename: string;
      /**
       * Generatedat
       * Format: date-time
       */
      generatedAt: string;
      /** Jobid */
      jobId: string;
      /** Ttsengine */
      ttsEngine: string;
      /** Url */
      url: string;
      /** Voice */
      voice: string;
    };
    /**
     * AudioFilter
     * @enum {string}
     */
    AudioFilter: "any" | "with" | "without";
    /** AutoExclusionUpdate */
    AutoExclusionUpdate: {
      /** Bookmarkids */
      bookmarkIds: string[];
      /** Excluded */
      excluded: boolean;
    };
    /** AutoGenerationSettings */
    AutoGenerationSettings: {
      /** Cron */
      cron: string;
      /** Enabled */
      enabled: boolean;
      /** Since */
      since?: string | null;
    };
    /** AutoGenerationStatus */
    AutoGenerationStatus: {
      /** Cron */
      cron: string;
      /** Enabled */
      enabled: boolean;
      /** Lasterror */
      lastError: string | null;
      /** Lastqueued */
      lastQueued: number | null;
      /** Lastrun */
      lastRun: string | null;
      /** Nextrun */
      nextRun: string | null;
      /** Since */
      since?: string | null;
    };
    /** Bookmark */
    Bookmark: {
      /**
       * Added
       * Format: date-time
       */
      added: string;
      audio: components["schemas"]["Audio"] | null;
      /** Authors */
      authors: string[];
      /** Autoexcluded */
      autoExcluded: boolean;
      /** Description */
      description: string;
      /** Id */
      id: string;
      job: components["schemas"]["BookmarkJob"] | null;
      /** Lang */
      lang: string;
      /** Published */
      published: string | null;
      /** Readingtime */
      readingTime: number | null;
      /** Sitename */
      siteName: string;
      /** Title */
      title: string;
      /** Type */
      type: string;
      /** Url */
      url: string;
    };
    /** BookmarkIds */
    BookmarkIds: {
      /** Bookmarkids */
      bookmarkIds: string[];
    };
    /** BookmarkJob */
    BookmarkJob: {
      /** Errormsg */
      errorMsg: string | null;
      /** Id */
      id: string;
      /**
       * Status
       * @enum {string}
       */
      status: "pending" | "processing" | "completed" | "failed";
    };
    /** BookmarkPage */
    BookmarkPage: {
      /** Items */
      items: components["schemas"]["Bookmark"][];
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Total */
      total: number;
      /** Totalpages */
      totalPages: number;
    };
    /** CountResult */
    CountResult: {
      /** Count */
      count: number;
    };
    /**
     * ExclusionFilter
     * @enum {string}
     */
    ExclusionFilter: "any" | "excluded" | "included";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
    };
    /** Job */
    Job: {
      /** Bookmarkid */
      bookmarkId: string;
      /** Bookmarktitle */
      bookmarkTitle: string;
      /** Bookmarkurl */
      bookmarkUrl: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      /** Errormsg */
      errorMsg: string | null;
      /** Id */
      id: string;
      /** Lang */
      lang: string;
      /**
       * Status
       * @enum {string}
       */
      status: "pending" | "processing" | "completed" | "failed";
      /** Ttsengine */
      ttsEngine: string;
      /** Updatedat */
      updatedAt: string | null;
      /** Voice */
      voice: string;
    };
    /** JobIds */
    JobIds: {
      /** Jobids */
      jobIds: string[];
    };
    /** JobPage */
    JobPage: {
      /** Items */
      items: components["schemas"]["Job"][];
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Total */
      total: number;
      /** Totalpages */
      totalPages: number;
    };
    /** QueueResult */
    QueueResult: {
      /** Queued */
      queued: number;
      /** Skipped */
      skipped: number;
    };
    /** Settings */
    Settings: {
      autoGeneration: components["schemas"]["AutoGenerationStatus"];
      sync: components["schemas"]["SyncStatus"];
    };
    /**
     * SettingsUpdate
     * @description Either section, or both; a section left out is unchanged.
     */
    SettingsUpdate: {
      autoGeneration?: components["schemas"]["AutoGenerationSettings"] | null;
      sync?: components["schemas"]["SyncSettings"] | null;
    };
    /** SyncSettings */
    SyncSettings: {
      /** Cron */
      cron: string;
    };
    /** SyncStatus */
    SyncStatus: {
      /** Added */
      added: number;
      /** Bookmarkcount */
      bookmarkCount: number;
      /** Cron */
      cron: string;
      /** Lasterror */
      lastError: string | null;
      /** Lastrun */
      lastRun: string | null;
      /** Nextrun */
      nextRun: string | null;
      /** Removed */
      removed: number;
      /** Running */
      running: boolean;
      /** Updated */
      updated: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  download_audio_api_audio__filename__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        filename: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  run_auto_generation_api_auto_generation_run_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueueResult"];
        };
      };
    };
  };
  list_bookmarks_api_bookmarks_get: {
    parameters: {
      query?: {
        page?: number;
        search?: string;
        audio?: components["schemas"]["AudioFilter"];
        autoGeneration?: components["schemas"]["ExclusionFilter"];
        addedFrom?: string | null;
        addedTo?: string | null;
        publishedFrom?: string | null;
        publishedTo?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookmarkPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_bookmark_audio_api_bookmarks_audio_delete_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookmarkIds"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CountResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_auto_exclusion_api_bookmarks_auto_generation_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AutoExclusionUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CountResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_jobs_api_jobs_get: {
    parameters: {
      query?: {
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_jobs_api_jobs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookmarkIds"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QueueResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bulk_delete_jobs_api_jobs_bulk_delete_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JobIds"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CountResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_job_ids_api_jobs_ids_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  get_job_api_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_job_api_jobs__job_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  retry_job_api_jobs__job_id__retry_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_settings_api_settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
    };
  };
  update_settings_api_settings_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  run_sync_api_sync_run_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
}
